trigger:
  batch: true
  branches:
    include:
      - master
      - 'refs/tags/ccf-*'

pr:
  autoCancel: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

schedules:
- cron: "0 3 * * Mon-Fri"
  displayName: Daily morning build
  branches:
    include:
    - master
  always: true

resources:
  containers:
    - container: nosgx
      image: ccfciteam/ccf-ci:oe0.10-npm
      options: --publish-all --cap-add SYS_PTRACE -v /dev/shm:/tmp/ccache -v /lib/modules:/lib/modules:ro

    - container: sgx
      image: ccfciteam/ccf-ci:oe0.10-npm
      options: --publish-all --device /dev/sgx:/dev/sgx -v /dev/shm:/tmp/ccache -v /lib/modules:/lib/modules:ro

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/ccf-') }}:
    perf_or_release: release
  ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/ccf-')) }}:
    perf_or_release: perf

jobs:
- template: .azure-pipelines-templates/matrix.yml
  parameters:
    perf_or_release: ${{ variables['perf_or_release'] }}
