- name: Include vars
  include_vars: common.yml

- name: Add NodeSource repository key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  become: yes

- name: Add NodeSource repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  become: yes

- name: Install Node.js
  apt:
    name: "nodejs"
    state: latest
    update_cache: yes
    install_recommends: no
  become: true
