jobs:
- job: GitHubRelease
  variables:
    skipComponentGovernanceDetection: true
  displayName: 'GitHub Release'
  dependsOn: ${{ parameters.depends_on }}

  ${{ insert }}: ${{ parameters.env }}

  steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: current
        patterns: '**/ccf*.deb'
        path: $(Build.ArtifactStagingDirectory)

    - task: GitHubRelease@0
      inputs:
        gitHubConnection: ccf_release
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'auto'
        assets: $(Build.ArtifactStagingDirectory)/**/ccf*.deb
        assetUploadMode: 'delete'
        isDraft: true
        isPreRelease: true
        addChangeLog: false
      displayName: 'GitHub release (create)'

    - script: |
        python3.7 -m venv env
        source ./env/bin/activate
        pip install -r requirements.txt
        pip install wheel twine
        python setup.py bdist_wheel
        twine upload -u __token__ -p $(pypi_token) dist/*
      workingDirectory: python
      displayName: PyPi https://pypi.org/project/ccf/